// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'third_party/localp2p_ffi/bridge.dart';

/// 外部发现的设备信息
class ExternalDiscovery {
  final String peerId;
  final String address;

  const ExternalDiscovery({required this.peerId, required this.address});

  @override
  int get hashCode => peerId.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExternalDiscovery &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          address == other.address;
}

/// P2P 事件（用于 FRB）
class P2PBridgeEvent {
  /// 事件类型
  /// 1 = NodeDiscovered
  /// 2 = NodeExpired
  /// 3 = NodeVerified
  /// 4 = NodeOffline
  /// 5 = UserInfoReceived
  /// 6 = MessageReceived
  /// 7 = MessageSent
  /// 8 = PeerTyping
  /// 9 = Log (Rust 日志)
  /// 10 = ServiceStatusChanged (服务状态变化)
  final int eventType;

  /// 事件数据 (JSON 字符串)
  final String data;

  const P2PBridgeEvent({required this.eventType, required this.data});

  @override
  int get hashCode => eventType.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is P2PBridgeEvent &&
          runtimeType == other.runtimeType &&
          eventType == other.eventType &&
          data == other.data;
}

/// 节点信息（用于 FRB）
class P2PBridgeNodeInfo {
  final String peerId;
  final String displayName;
  final String deviceName;
  final String? nickname;
  final String? status;
  final String? avatarUrl;

  /// 节点地址列表（例如: ["/ip4/192.168.1.100/tcp/50001"]）
  final List<String> addresses;

  /// 协议版本（例如: "/localp2p/1.0.0"）
  final String protocolVersion;

  const P2PBridgeNodeInfo({
    required this.peerId,
    required this.displayName,
    required this.deviceName,
    this.nickname,
    this.status,
    this.avatarUrl,
    required this.addresses,
    required this.protocolVersion,
  });

  /// 简化版本，只有基本信息（用于兼容旧代码）
  static Future<P2PBridgeNodeInfo> fromBasicInfo({
    required String peerId,
    required String displayName,
    required String deviceName,
  }) => RustLib.instance.api.crateBridgeP2PBridgeNodeInfoFromBasicInfo(
    peerId: peerId,
    displayName: displayName,
    deviceName: deviceName,
  );

  static Future<P2PBridgeNodeInfo> fromPeerIdAndInfo({
    required String peerId,
    required UserInfo info,
  }) => RustLib.instance.api.crateBridgeP2PBridgeNodeInfoFromPeerIdAndInfo(
    peerId: peerId,
    info: info,
  );

  @override
  int get hashCode =>
      peerId.hashCode ^
      displayName.hashCode ^
      deviceName.hashCode ^
      nickname.hashCode ^
      status.hashCode ^
      avatarUrl.hashCode ^
      addresses.hashCode ^
      protocolVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is P2PBridgeNodeInfo &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          displayName == other.displayName &&
          deviceName == other.deviceName &&
          nickname == other.nickname &&
          status == other.status &&
          avatarUrl == other.avatarUrl &&
          addresses == other.addresses &&
          protocolVersion == other.protocolVersion;
}

/// 🔥 服务健康状态（用于 FRB）
enum ServiceHealthJson { healthy, degraded, unhealthy }

/// 🔥 服务状态（用于 FRB）
class ServiceStatusJson {
  final String name;
  final ServiceHealthJson health;
  final bool isRunning;
  final String? message;

  const ServiceStatusJson({
    required this.name,
    required this.health,
    required this.isRunning,
    this.message,
  });

  @override
  int get hashCode =>
      name.hashCode ^ health.hashCode ^ isRunning.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServiceStatusJson &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          health == other.health &&
          isRunning == other.isRunning &&
          message == other.message;
}

/// 🔥 系统状态（用于 FRB）
class SystemStatusJson {
  final ServiceStatusJson mdnsService;
  final ServiceStatusJson connectionService;
  final BigInt connectedPeers;
  final BigInt discoveredPeers;

  const SystemStatusJson({
    required this.mdnsService,
    required this.connectionService,
    required this.connectedPeers,
    required this.discoveredPeers,
  });

  @override
  int get hashCode =>
      mdnsService.hashCode ^
      connectionService.hashCode ^
      connectedPeers.hashCode ^
      discoveredPeers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SystemStatusJson &&
          runtimeType == other.runtimeType &&
          mdnsService == other.mdnsService &&
          connectionService == other.connectionService &&
          connectedPeers == other.connectedPeers &&
          discoveredPeers == other.discoveredPeers;
}
