// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'types.dart';
part 'lib.freezed.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<* const c_char>>
abstract class ConstCChar implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<* mut c_char>>
abstract class MutCChar implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<* mut * mut c_char>>
abstract class MutMutCChar implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<size_t>>
abstract class SizeT implements RustOpaqueInterface {}

@freezed
sealed class P2PEvent with _$P2PEvent {
  const P2PEvent._();

  const factory P2PEvent.nodeDiscovered({
    required String peerId,
    required String addr,
  }) = P2PEvent_NodeDiscovered;
  const factory P2PEvent.nodeExpired({required String peerId}) =
      P2PEvent_NodeExpired;
  const factory P2PEvent.nodeVerified({
    required String peerId,
    required String displayName,
  }) = P2PEvent_NodeVerified;
  const factory P2PEvent.nodeOffline({required String peerId}) =
      P2PEvent_NodeOffline;
  const factory P2PEvent.userInfoReceived({
    required String peerId,
    required UserInfoJson userInfo,
  }) = P2PEvent_UserInfoReceived;
  const factory P2PEvent.messageReceived({
    required String from,
    required ChatMessageJson message,
  }) = P2PEvent_MessageReceived;
  const factory P2PEvent.messageSent({
    required String to,
    required String messageId,
  }) = P2PEvent_MessageSent;
  const factory P2PEvent.peerTyping({
    required String from,
    required bool isTyping,
  }) = P2PEvent_PeerTyping;
}
