// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CStrView>>
abstract class CStrView implements RustOpaqueInterface {
  /// 转换为 Rust 字符串切片（unsafe）
  ///
  /// # Safety
  /// 调用者必须确保原始字符串仍然有效
  Future<void> asStr();

  /// 从 Rust 字符串创建
  static Future<CStrView> fromStr({required String s}) =>
      P2PBridge.instance.api.crateTypesCStrViewFromStr(s: s);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<P2PEventData>>
abstract class P2PEventData implements RustOpaqueInterface {
  static Future<P2PEventData> default_() =>
      P2PBridge.instance.api.crateTypesP2PEventDataDefault();
}

/// JSON 序列化的聊天消息
class ChatMessageJson {
  final String id;
  final String senderPeerId;
  final String content;
  final PlatformInt64 timestamp;

  const ChatMessageJson({
    required this.id,
    required this.senderPeerId,
    required this.content,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      senderPeerId.hashCode ^
      content.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageJson &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          senderPeerId == other.senderPeerId &&
          content == other.content &&
          timestamp == other.timestamp;
}

/// P2P 错误代码
enum P2PErrorCode {
  /// 成功
  success,

  /// 未初始化
  notInitialized,

  /// 无效参数
  invalidArgument,

  /// 发送失败
  sendFailed,

  /// 节点未验证
  nodeNotVerified,

  /// 内存不足
  outOfMemory,

  /// 其他错误
  unknown,
}

/// P2P 不透明句柄
///
/// 用于标识 P2P 实例
class P2PHandle {
  final int private;

  const P2PHandle({required this.private});

  @override
  int get hashCode => private.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is P2PHandle &&
          runtimeType == other.runtimeType &&
          private == other.private;
}

/// JSON 序列化的用户信息
class UserInfoJson {
  final String deviceName;
  final String? nickname;
  final String? avatarUrl;
  final String? status;

  const UserInfoJson({
    required this.deviceName,
    this.nickname,
    this.avatarUrl,
    this.status,
  });

  @override
  int get hashCode =>
      deviceName.hashCode ^
      nickname.hashCode ^
      avatarUrl.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserInfoJson &&
          runtimeType == other.runtimeType &&
          deviceName == other.deviceName &&
          nickname == other.nickname &&
          avatarUrl == other.avatarUrl &&
          status == other.status;
}
