// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'bridge.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'third_party/localp2p_ffi/bridge.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -238510421;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'localp2p_ffi',
        ioDirectory: '../crates/ffi/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  void localp2PFfiBridgeP2PBroadcastMessage({
    required List<String> targetPeerIds,
    required String message,
  });

  void localp2PFfiBridgeP2PCleanup();

  String localp2PFfiBridgeP2PGetDeviceName();

  String localp2PFfiBridgeP2PGetLocalPeerId();

  List<P2PBridgeNodeInfo> localp2PFfiBridgeP2PGetVerifiedNodes();

  void localp2PFfiBridgeP2PInit({
    required String deviceName,
    required String identityPath,
  });

  bool localp2PFfiBridgeP2PIsDiscoveryThreadAlive();

  bool localp2PFfiBridgeP2PIsInitialized();

  bool localp2PFfiBridgeP2PIsRunning();

  List<P2PBridgeEvent> localp2PFfiBridgeP2PPollEvents();

  void localp2PFfiBridgeP2PRestartDiscovery();

  void localp2PFfiBridgeP2PSendMessage({
    required String targetPeerId,
    required String message,
  });

  Stream<P2PBridgeEvent> localp2PFfiBridgeP2PSetEventStream();

  void localp2PFfiBridgeP2PStart();

  void localp2PFfiBridgeP2PStop();

  Future<P2PBridgeNodeInfo> crateBridgeP2PBridgeNodeInfoFromBasicInfo({
    required String peerId,
    required String displayName,
    required String deviceName,
  });

  Future<P2PBridgeNodeInfo> crateBridgeP2PBridgeNodeInfoFromPeerIdAndInfo({
    required String peerId,
    required UserInfo info,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_UserInfo;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_UserInfo;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_UserInfoPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void localp2PFfiBridgeP2PBroadcastMessage({
    required List<String> targetPeerIds,
    required String message,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(targetPeerIds, serializer);
          sse_encode_String(message, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kLocalp2PFfiBridgeP2PBroadcastMessageConstMeta,
        argValues: [targetPeerIds, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kLocalp2PFfiBridgeP2PBroadcastMessageConstMeta =>
      const TaskConstMeta(
        debugName: "p2p_broadcast_message",
        argNames: ["targetPeerIds", "message"],
      );

  @override
  void localp2PFfiBridgeP2PCleanup() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kLocalp2PFfiBridgeP2PCleanupConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kLocalp2PFfiBridgeP2PCleanupConstMeta =>
      const TaskConstMeta(debugName: "p2p_cleanup", argNames: []);

  @override
  String localp2PFfiBridgeP2PGetDeviceName() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kLocalp2PFfiBridgeP2PGetDeviceNameConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kLocalp2PFfiBridgeP2PGetDeviceNameConstMeta =>
      const TaskConstMeta(debugName: "p2p_get_device_name", argNames: []);

  @override
  String localp2PFfiBridgeP2PGetLocalPeerId() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kLocalp2PFfiBridgeP2PGetLocalPeerIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kLocalp2PFfiBridgeP2PGetLocalPeerIdConstMeta =>
      const TaskConstMeta(debugName: "p2p_get_local_peer_id", argNames: []);

  @override
  List<P2PBridgeNodeInfo> localp2PFfiBridgeP2PGetVerifiedNodes() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_p_2_p_bridge_node_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kLocalp2PFfiBridgeP2PGetVerifiedNodesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kLocalp2PFfiBridgeP2PGetVerifiedNodesConstMeta =>
      const TaskConstMeta(debugName: "p2p_get_verified_nodes", argNames: []);

  @override
  void localp2PFfiBridgeP2PInit({
    required String deviceName,
    required String identityPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceName, serializer);
          sse_encode_String(identityPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kLocalp2PFfiBridgeP2PInitConstMeta,
        argValues: [deviceName, identityPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kLocalp2PFfiBridgeP2PInitConstMeta => const TaskConstMeta(
    debugName: "p2p_init",
    argNames: ["deviceName", "identityPath"],
  );

  @override
  bool localp2PFfiBridgeP2PIsDiscoveryThreadAlive() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kLocalp2PFfiBridgeP2PIsDiscoveryThreadAliveConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kLocalp2PFfiBridgeP2PIsDiscoveryThreadAliveConstMeta =>
      const TaskConstMeta(
        debugName: "p2p_is_discovery_thread_alive",
        argNames: [],
      );

  @override
  bool localp2PFfiBridgeP2PIsInitialized() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kLocalp2PFfiBridgeP2PIsInitializedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kLocalp2PFfiBridgeP2PIsInitializedConstMeta =>
      const TaskConstMeta(debugName: "p2p_is_initialized", argNames: []);

  @override
  bool localp2PFfiBridgeP2PIsRunning() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kLocalp2PFfiBridgeP2PIsRunningConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kLocalp2PFfiBridgeP2PIsRunningConstMeta =>
      const TaskConstMeta(debugName: "p2p_is_running", argNames: []);

  @override
  List<P2PBridgeEvent> localp2PFfiBridgeP2PPollEvents() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_p_2_p_bridge_event,
          decodeErrorData: null,
        ),
        constMeta: kLocalp2PFfiBridgeP2PPollEventsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kLocalp2PFfiBridgeP2PPollEventsConstMeta =>
      const TaskConstMeta(debugName: "p2p_poll_events", argNames: []);

  @override
  void localp2PFfiBridgeP2PRestartDiscovery() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kLocalp2PFfiBridgeP2PRestartDiscoveryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kLocalp2PFfiBridgeP2PRestartDiscoveryConstMeta =>
      const TaskConstMeta(debugName: "p2p_restart_discovery", argNames: []);

  @override
  void localp2PFfiBridgeP2PSendMessage({
    required String targetPeerId,
    required String message,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(targetPeerId, serializer);
          sse_encode_String(message, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kLocalp2PFfiBridgeP2PSendMessageConstMeta,
        argValues: [targetPeerId, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kLocalp2PFfiBridgeP2PSendMessageConstMeta =>
      const TaskConstMeta(
        debugName: "p2p_send_message",
        argNames: ["targetPeerId", "message"],
      );

  @override
  Stream<P2PBridgeEvent> localp2PFfiBridgeP2PSetEventStream() {
    final streamSink = RustStreamSink<P2PBridgeEvent>();
    handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_StreamSink_p_2_p_bridge_event_Sse(streamSink, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kLocalp2PFfiBridgeP2PSetEventStreamConstMeta,
        argValues: [streamSink],
        apiImpl: this,
      ),
    );
    return streamSink.stream;
  }

  TaskConstMeta get kLocalp2PFfiBridgeP2PSetEventStreamConstMeta =>
      const TaskConstMeta(
        debugName: "p2p_set_event_stream",
        argNames: ["streamSink"],
      );

  @override
  void localp2PFfiBridgeP2PStart() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kLocalp2PFfiBridgeP2PStartConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kLocalp2PFfiBridgeP2PStartConstMeta =>
      const TaskConstMeta(debugName: "p2p_start", argNames: []);

  @override
  void localp2PFfiBridgeP2PStop() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kLocalp2PFfiBridgeP2PStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kLocalp2PFfiBridgeP2PStopConstMeta =>
      const TaskConstMeta(debugName: "p2p_stop", argNames: []);

  @override
  Future<P2PBridgeNodeInfo> crateBridgeP2PBridgeNodeInfoFromBasicInfo({
    required String peerId,
    required String displayName,
    required String deviceName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_String(displayName, serializer);
          sse_encode_String(deviceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_p_2_p_bridge_node_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeP2PBridgeNodeInfoFromBasicInfoConstMeta,
        argValues: [peerId, displayName, deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeP2PBridgeNodeInfoFromBasicInfoConstMeta =>
      const TaskConstMeta(
        debugName: "p_2_p_bridge_node_info_from_basic_info",
        argNames: ["peerId", "displayName", "deviceName"],
      );

  @override
  Future<P2PBridgeNodeInfo> crateBridgeP2PBridgeNodeInfoFromPeerIdAndInfo({
    required String peerId,
    required UserInfo info,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserInfo(
            info,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_p_2_p_bridge_node_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeP2PBridgeNodeInfoFromPeerIdAndInfoConstMeta,
        argValues: [peerId, info],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeP2PBridgeNodeInfoFromPeerIdAndInfoConstMeta =>
      const TaskConstMeta(
        debugName: "p_2_p_bridge_node_info_from_peer_id_and_info",
        argNames: ["peerId", "info"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_UserInfo => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserInfo;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_UserInfo => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserInfo;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  UserInfo
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserInfo(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UserInfoImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  UserInfo
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserInfo(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UserInfoImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<P2PBridgeEvent> dco_decode_StreamSink_p_2_p_bridge_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<P2PBridgeEvent> dco_decode_list_p_2_p_bridge_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_p_2_p_bridge_event).toList();
  }

  @protected
  List<P2PBridgeNodeInfo> dco_decode_list_p_2_p_bridge_node_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_p_2_p_bridge_node_info)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  P2PBridgeEvent dco_decode_p_2_p_bridge_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return P2PBridgeEvent(
      eventType: dco_decode_i_32(arr[0]),
      data: dco_decode_String(arr[1]),
    );
  }

  @protected
  P2PBridgeNodeInfo dco_decode_p_2_p_bridge_node_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return P2PBridgeNodeInfo(
      peerId: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      deviceName: dco_decode_String(arr[2]),
      nickname: dco_decode_opt_String(arr[3]),
      status: dco_decode_opt_String(arr[4]),
      avatarUrl: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  UserInfo
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserInfo(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return UserInfoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  UserInfo
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserInfo(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return UserInfoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<P2PBridgeEvent> sse_decode_StreamSink_p_2_p_bridge_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<P2PBridgeEvent> sse_decode_list_p_2_p_bridge_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <P2PBridgeEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_p_2_p_bridge_event(deserializer));
    }
    return ans_;
  }

  @protected
  List<P2PBridgeNodeInfo> sse_decode_list_p_2_p_bridge_node_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <P2PBridgeNodeInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_p_2_p_bridge_node_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  P2PBridgeEvent sse_decode_p_2_p_bridge_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eventType = sse_decode_i_32(deserializer);
    var var_data = sse_decode_String(deserializer);
    return P2PBridgeEvent(eventType: var_eventType, data: var_data);
  }

  @protected
  P2PBridgeNodeInfo sse_decode_p_2_p_bridge_node_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_nickname = sse_decode_opt_String(deserializer);
    var var_status = sse_decode_opt_String(deserializer);
    var var_avatarUrl = sse_decode_opt_String(deserializer);
    return P2PBridgeNodeInfo(
      peerId: var_peerId,
      displayName: var_displayName,
      deviceName: var_deviceName,
      nickname: var_nickname,
      status: var_status,
      avatarUrl: var_avatarUrl,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserInfo(
    UserInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as UserInfoImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserInfo(
    UserInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as UserInfoImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_p_2_p_bridge_event_Sse(
    RustStreamSink<P2PBridgeEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_p_2_p_bridge_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_p_2_p_bridge_event(
    List<P2PBridgeEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_p_2_p_bridge_event(item, serializer);
    }
  }

  @protected
  void sse_encode_list_p_2_p_bridge_node_info(
    List<P2PBridgeNodeInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_p_2_p_bridge_node_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_p_2_p_bridge_event(
    P2PBridgeEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.eventType, serializer);
    sse_encode_String(self.data, serializer);
  }

  @protected
  void sse_encode_p_2_p_bridge_node_info(
    P2PBridgeNodeInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_opt_String(self.nickname, serializer);
    sse_encode_opt_String(self.status, serializer);
    sse_encode_opt_String(self.avatarUrl, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class UserInfoImpl extends RustOpaque implements UserInfo {
  // Not to be used by end users
  UserInfoImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  UserInfoImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_UserInfo,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_UserInfo,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_UserInfoPtr,
  );
}
