// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 会话信息
class ConversationJson {
  final String id;
  final String peerId;
  final String? peerName;
  final String? peerAvatar;
  final String? lastMessage;
  final int lastMessageType;
  final PlatformInt64? lastMessageTime;
  final int unreadCount;
  final bool isPinned;
  final bool isMuted;

  const ConversationJson({
    required this.id,
    required this.peerId,
    this.peerName,
    this.peerAvatar,
    this.lastMessage,
    required this.lastMessageType,
    this.lastMessageTime,
    required this.unreadCount,
    required this.isPinned,
    required this.isMuted,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      peerId.hashCode ^
      peerName.hashCode ^
      peerAvatar.hashCode ^
      lastMessage.hashCode ^
      lastMessageType.hashCode ^
      lastMessageTime.hashCode ^
      unreadCount.hashCode ^
      isPinned.hashCode ^
      isMuted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationJson &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          peerId == other.peerId &&
          peerName == other.peerName &&
          peerAvatar == other.peerAvatar &&
          lastMessage == other.lastMessage &&
          lastMessageType == other.lastMessageType &&
          lastMessageTime == other.lastMessageTime &&
          unreadCount == other.unreadCount &&
          isPinned == other.isPinned &&
          isMuted == other.isMuted;
}

/// 文件元数据
class FileInfoJson {
  final String id;
  final String messageId;
  final String fileName;
  final PlatformInt64 fileSize;
  final String mimeType;
  final String? localPath;
  final String? thumbnailPath;
  final int? duration;
  final int? width;
  final int? height;
  final int transferStatus;
  final int transferProgress;

  const FileInfoJson({
    required this.id,
    required this.messageId,
    required this.fileName,
    required this.fileSize,
    required this.mimeType,
    this.localPath,
    this.thumbnailPath,
    this.duration,
    this.width,
    this.height,
    required this.transferStatus,
    required this.transferProgress,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      messageId.hashCode ^
      fileName.hashCode ^
      fileSize.hashCode ^
      mimeType.hashCode ^
      localPath.hashCode ^
      thumbnailPath.hashCode ^
      duration.hashCode ^
      width.hashCode ^
      height.hashCode ^
      transferStatus.hashCode ^
      transferProgress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileInfoJson &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          messageId == other.messageId &&
          fileName == other.fileName &&
          fileSize == other.fileSize &&
          mimeType == other.mimeType &&
          localPath == other.localPath &&
          thumbnailPath == other.thumbnailPath &&
          duration == other.duration &&
          width == other.width &&
          height == other.height &&
          transferStatus == other.transferStatus &&
          transferProgress == other.transferProgress;
}

/// 扩展消息信息
class MessageJson {
  final String id;
  final String conversationId;
  final String senderPeerId;
  final int messageType;
  final String content;
  final PlatformInt64 timestamp;
  final String? replyToId;
  final int status;
  final bool isDeleted;
  final bool isRevoked;

  const MessageJson({
    required this.id,
    required this.conversationId,
    required this.senderPeerId,
    required this.messageType,
    required this.content,
    required this.timestamp,
    this.replyToId,
    required this.status,
    required this.isDeleted,
    required this.isRevoked,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      conversationId.hashCode ^
      senderPeerId.hashCode ^
      messageType.hashCode ^
      content.hashCode ^
      timestamp.hashCode ^
      replyToId.hashCode ^
      status.hashCode ^
      isDeleted.hashCode ^
      isRevoked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageJson &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          conversationId == other.conversationId &&
          senderPeerId == other.senderPeerId &&
          messageType == other.messageType &&
          content == other.content &&
          timestamp == other.timestamp &&
          replyToId == other.replyToId &&
          status == other.status &&
          isDeleted == other.isDeleted &&
          isRevoked == other.isRevoked;
}
